# Ticket: Connection
# Rename this file to .ini after filling in your MFLIX_DB_URI and your SECRET_KEY
# Do not surround the URI with quotes

[PROD]
SECRET_KEY = kjhsldakjhflskdfjchlwkjhr983kjfhlkjdshf987fskdjhfkdsjhfi7y4onhfli
MFLIX_DB_URI = mongodb+srv://mflixAppUser:mflixAppPwd@mflix-z2gcx.mongodb.net/test?retryWrites=true&w=majority
MFLIX_NS = sample_mflix

[TEST]
SECRET_KEY = nlkhfco4873yr34pnvoiugtpv92853nyp98mup9nru314p9r8n3u4pr98nrkjhlkfnhsa8
MFLIX_DB_URI = mongodb+srv://mflixAppUser:mflixAppPwd@mflix-z2gcx.mongodb.net/test?retryWrites=true&w=majority
MFLIX_NS = sample_mflix
